version: '3.8'

services:
  triton_server:
    image: triton_llm_server
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"  # HTTP
      - "8001:8001"  # gRPC
      - "8002:8002"  # Metrics
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    command: ["tritonserver", "--model-repository=/triton_llm/models", "--disable-auto-complete-config"]